### ISSUE TITLE
Unexpected Error with the plugin

### ISSUE THREAD

**Issue by FallenEmo** [DSlyDog/TimTheEnchanter#2]
21.04 20:45:34 [Server] INFO Caused by: java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: Power
21.04 20:45:34 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
21.04 20:45:34 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'enchant' in plugin TimTheEnchanter v2.0
21.04 20:45:34 [Server] Server thread/ERROR null
21.04 20:45:34 [Server] Server thread/INFO FallenEmo16 issued server command: /enchant Power 10

**Comment by DSlyDog** [comment]
Hi, thanks for posting this. This error only happens when you try to use the enchant command with nothing in your main hand. I added some checks into an update I will be releasing very soon, so this error should no longer appear.
